version: "3.8"

services:
  aws-localstack:
    container_name: aws-localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8000}:${PORT_WEB_UI-8000}"
    environment:
      - SERVICES=secretsmanager,ssm,sts,acm,dynamodb
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=AKIA6ISFFOL2UYYT3WX4
      - AWS_SECRET_ACCESS_KEY=fa50bf94-d965-452b-ae1a-18ffa47ed90f
      - AWS_DEFAULT_REGION=sa-east-1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - START_WEB=1
      - LEGACY_DIRECTORIES=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - dev-net

  aws-secrets-manager:
    container_name: aws-secrets-manager
    image: amazon/aws-cli
    depends_on:
      - aws-localstack
    entrypoint: /bin/sh -c
    command: >
      "aws --endpoint http://host.docker.internal:4566 secretsmanager create-secret --name 'sts-credentials-test' --description 'Segredo para efetuar um teste com LocalStack' --secret-string '{\"client-id\":\"fakeaccess\",\"client-secret\":\"fakesecret\"}' --region 'sa-east-1'"
    restart: on-failure:5
    environment:
      AWS_ACCESS_KEY_ID: AKIA6ISFFOL2UYYT3WX4
      AWS_SECRET_ACCESS_KEY: fa50bf94-d965-452b-ae1a-18ffa47ed90f
      AWS_DEFAULT_REGION: sa-east-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - dev-net
      
  mysql-local:
    container_name: mysql_local
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "System@20"
      MYSQL_DATABASE: "coffemachine"
    ports:
      - "3306:3306"
    volumes:
      - mysql-local:/var/lib/mysql
    networks:
      - dev-net

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_local
    ports:
      - "8080:8080"
    networks:
      - dev-net

networks:
  dev-net:
    driver:
      bridge
      
volumes:
  mysql-local: